package io.github.juanmuscaria.jmutils.discord.game.struct;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class DiscordUserAchievement extends Structure {
    public long user_id;
    public long achievement_id;
    public byte percent_complete;
    public byte[] unlocked_at = new byte[64];

    public DiscordUserAchievement() {
        super();
    }

    public DiscordUserAchievement(long user_id, long achievement_id, byte percent_complete, byte[] unlocked_at) {
        super();
        this.user_id = user_id;
        this.achievement_id = achievement_id;
        this.percent_complete = percent_complete;
        if ((unlocked_at.length != this.unlocked_at.length))
            throw new IllegalArgumentException("Wrong array size !");
        this.unlocked_at = unlocked_at;
    }

    public DiscordUserAchievement(Pointer peer) {
        super(peer);
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("user_id", "achievement_id", "percent_complete", "unlocked_at");
    }

    public static class ByReference extends DiscordUserAchievement implements Structure.ByReference {

    }

    public static class ByValue extends DiscordUserAchievement implements Structure.ByValue {

    }

}
