package io.github.juanmuscaria.jmutils.discord.game.struct;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class DiscordLobby extends Structure {
    public long id;
    public int type;
    public long owner_id;
    public byte[] secret = new byte[128];
    public int capacity;
    public byte locked;

    public DiscordLobby() {
        super();
    }

    public DiscordLobby(long id, int type, long owner_id, byte[] secret, int capacity, byte locked) {
        super();
        this.id = id;
        this.type = type;
        this.owner_id = owner_id;
        if ((secret.length != this.secret.length))
            throw new IllegalArgumentException("Wrong array size !");
        this.secret = secret;
        this.capacity = capacity;
        this.locked = locked;
    }

    public DiscordLobby(Pointer peer) {
        super(peer);
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("id", "type", "owner_id", "secret", "capacity", "locked");
    }

    public static class ByReference extends DiscordLobby implements Structure.ByReference {

    }

    public static class ByValue extends DiscordLobby implements Structure.ByValue {

    }
}
