package io.github.juanmuscaria.jmutils.discord.game.struct;

import com.sun.jna.Callback;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class IDiscordLobbyMemberTransaction extends Structure {
    public set_metadata_callback set_metadata;
    public delete_metadata_callback delete_metadata;

    public IDiscordLobbyMemberTransaction() {
        super();
    }

    public IDiscordLobbyMemberTransaction(set_metadata_callback set_metadata, delete_metadata_callback delete_metadata) {
        super();
        this.set_metadata = set_metadata;
        this.delete_metadata = delete_metadata;
    }

    public IDiscordLobbyMemberTransaction(Pointer peer) {
        super(peer);
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("set_metadata", "delete_metadata");
    }

    public interface set_metadata_callback extends Callback {
        int apply(IDiscordLobbyMemberTransaction lobby_member_transaction, Pointer key, Pointer value);
    }

    public interface delete_metadata_callback extends Callback {
        int apply(IDiscordLobbyMemberTransaction lobby_member_transaction, Pointer key);
    }

    public static class ByReference extends IDiscordLobbyMemberTransaction implements Structure.ByReference {

    }

    public static class ByValue extends IDiscordLobbyMemberTransaction implements Structure.ByValue {

    }

}
