package io.github.juanmuscaria.jmutils.discord.game.struct;

import com.sun.jna.Callback;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class IDiscordLobbySearchQuery extends Structure {
    public IDiscordRelationshipManager.filter_callback filter;
    public sort_callback sort;
    public limit_callback limit;
    public distance_callback distance;

    public IDiscordLobbySearchQuery() {
        super();
    }

    public IDiscordLobbySearchQuery(IDiscordRelationshipManager.filter_callback filter, sort_callback sort, limit_callback limit, distance_callback distance) {
        super();
        this.filter = filter;
        this.sort = sort;
        this.limit = limit;
        this.distance = distance;
    }

    public IDiscordLobbySearchQuery(Pointer peer) {
        super(peer);
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("filter", "sort", "limit", "distance");
    }

    public interface filter_callback extends Callback {
        int apply(IDiscordLobbySearchQuery lobby_search_query, Pointer key, int comparison, int cast, Pointer value);
    }

    public interface sort_callback extends Callback {
        int apply(IDiscordLobbySearchQuery lobby_search_query, Pointer key, int cast, Pointer value);
    }

    public interface limit_callback extends Callback {
        int apply(IDiscordLobbySearchQuery lobby_search_query, int limit);
    }

    public interface distance_callback extends Callback {
        int apply(IDiscordLobbySearchQuery lobby_search_query, int distance);
    }

    public static class ByReference extends IDiscordLobbySearchQuery implements Structure.ByReference {

    }

    public static class ByValue extends IDiscordLobbySearchQuery implements Structure.ByValue {

    }

}
