package io.github.juanmuscaria.jmutils.discord.game.struct;

import com.sun.jna.Callback;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class IDiscordOverlayManager extends Structure {
    public is_enabled_callback is_enabled;
    public is_locked_callback is_locked;
    public set_locked_callback set_locked;
    public open_activity_invite_callback open_activity_invite;
    public open_guild_invite_callback open_guild_invite;
    public open_voice_settings_callback open_voice_settings;

    public IDiscordOverlayManager() {
        super();
    }

    public IDiscordOverlayManager(is_enabled_callback is_enabled, is_locked_callback is_locked, set_locked_callback set_locked, open_activity_invite_callback open_activity_invite, open_guild_invite_callback open_guild_invite, open_voice_settings_callback open_voice_settings) {
        super();
        this.is_enabled = is_enabled;
        this.is_locked = is_locked;
        this.set_locked = set_locked;
        this.open_activity_invite = open_activity_invite;
        this.open_guild_invite = open_guild_invite;
        this.open_voice_settings = open_voice_settings;
    }

    public IDiscordOverlayManager(Pointer peer) {
        super(peer);
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("is_enabled", "is_locked", "set_locked", "open_activity_invite", "open_guild_invite", "open_voice_settings");
    }

    public interface is_enabled_callback extends Callback {
        void apply(IDiscordOverlayManager manager, Pointer enabled);
    }

    public interface is_locked_callback extends Callback {
        void apply(IDiscordOverlayManager manager, Pointer locked);
    }

    public interface set_locked_callback_callback_callback extends Callback {
        void apply(Pointer callback_data, int result);
    }

    public interface set_locked_callback extends Callback {
        void apply(IDiscordOverlayManager manager, byte locked, Pointer callback_data, set_locked_callback_callback_callback callback);
    }

    public interface open_activity_invite_callback_callback_callback extends Callback {
        void apply(Pointer callback_data, int result);
    }

    public interface open_activity_invite_callback extends Callback {
        void apply(IDiscordOverlayManager manager, int type, Pointer callback_data, open_activity_invite_callback_callback_callback callback);
    }

    public interface open_guild_invite_callback_callback_callback extends Callback {
        void apply(Pointer callback_data, int result);
    }

    public interface open_guild_invite_callback extends Callback {
        void apply(IDiscordOverlayManager manager, Pointer code, Pointer callback_data, open_guild_invite_callback_callback_callback callback);
    }

    public interface open_voice_settings_callback_callback_callback extends Callback {
        void apply(Pointer callback_data, int result);
    }

    public interface open_voice_settings_callback extends Callback {
        void apply(IDiscordOverlayManager manager, Pointer callback_data, open_voice_settings_callback_callback_callback callback);
    }

    public static class ByReference extends IDiscordOverlayManager implements Structure.ByReference {

    }

    public static class ByValue extends IDiscordOverlayManager implements Structure.ByValue {

    }

}
