package io.github.juanmuscaria.jmutils.discord.game.struct;

import com.sun.jna.Callback;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class IDiscordActivityEvents extends Structure {
    public on_activity_join_callback on_activity_join;
    public on_activity_spectate_callback on_activity_spectate;
    public on_activity_join_request_callback on_activity_join_request;
    public on_activity_invite_callback on_activity_invite;

    public IDiscordActivityEvents() {
        super();
    }

    public IDiscordActivityEvents(on_activity_join_callback on_activity_join, on_activity_spectate_callback on_activity_spectate, on_activity_join_request_callback on_activity_join_request, on_activity_invite_callback on_activity_invite) {
        super();
        this.on_activity_join = on_activity_join;
        this.on_activity_spectate = on_activity_spectate;
        this.on_activity_join_request = on_activity_join_request;
        this.on_activity_invite = on_activity_invite;
    }

    public IDiscordActivityEvents(Pointer peer) {
        super(peer);
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("on_activity_join", "on_activity_spectate", "on_activity_join_request", "on_activity_invite");
    }

    public interface on_activity_join_callback extends Callback {
        void apply(Pointer event_data, Pointer secret);
    }

    public interface on_activity_spectate_callback extends Callback {
        void apply(Pointer event_data, Pointer secret);
    }

    public interface on_activity_join_request_callback extends Callback {
        void apply(Pointer event_data, DiscordUser user);
    }

    public interface on_activity_invite_callback extends Callback {
        void apply(Pointer event_data, int type, DiscordUser user, DiscordActivity activity);
    }

    public static class ByReference extends IDiscordActivityEvents implements Structure.ByReference {

    }

    public static class ByValue extends IDiscordActivityEvents implements Structure.ByValue {

    }

}
