package io.github.juanmuscaria.jmutils.discord.game.struct;

import com.sun.jna.Callback;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class IDiscordLobbyTransaction extends Structure {
    public set_type_callback set_type;
    public set_owner_callback set_owner;
    public set_capacity_callback set_capacity;
    public IDiscordLobbyMemberTransaction.set_metadata_callback set_metadata;
    public IDiscordLobbyMemberTransaction.delete_metadata_callback delete_metadata;
    public IDiscordOverlayManager.set_locked_callback set_locked;

    public IDiscordLobbyTransaction() {
        super();
    }

    public IDiscordLobbyTransaction(set_type_callback set_type, set_owner_callback set_owner, set_capacity_callback set_capacity, IDiscordLobbyMemberTransaction.set_metadata_callback set_metadata, IDiscordLobbyMemberTransaction.delete_metadata_callback delete_metadata, IDiscordOverlayManager.set_locked_callback set_locked) {
        super();
        this.set_type = set_type;
        this.set_owner = set_owner;
        this.set_capacity = set_capacity;
        this.set_metadata = set_metadata;
        this.delete_metadata = delete_metadata;
        this.set_locked = set_locked;
    }

    public IDiscordLobbyTransaction(Pointer peer) {
        super(peer);
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("set_type", "set_owner", "set_capacity", "set_metadata", "delete_metadata", "set_locked");
    }

    public interface set_type_callback extends Callback {
        int apply(IDiscordLobbyTransaction lobby_transaction, int type);
    }

    public interface set_owner_callback extends Callback {
        int apply(IDiscordLobbyTransaction lobby_transaction, long owner_id);
    }

    public interface set_capacity_callback extends Callback {
        int apply(IDiscordLobbyTransaction lobby_transaction, int capacity);
    }

    public interface set_metadata_callback extends Callback {
        int apply(IDiscordLobbyTransaction lobby_transaction, Pointer key, Pointer value);
    }

    public interface delete_metadata_callback extends Callback {
        int apply(IDiscordLobbyTransaction lobby_transaction, Pointer key);
    }

    public interface set_locked_callback extends Callback {
        int apply(IDiscordLobbyTransaction lobby_transaction, byte locked);
    }

    public static class ByReference extends IDiscordLobbyTransaction implements Structure.ByReference {

    }

    public static class ByValue extends IDiscordLobbyTransaction implements Structure.ByValue {

    }

}
