package io.github.juanmuscaria.jmutils.discord.game.struct;

import com.sun.jna.Callback;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import com.sun.jna.ptr.IntByReference;

import java.util.Arrays;
import java.util.List;

/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class IDiscordStoreManager extends Structure {
    public fetch_skus_callback fetch_skus;
    public count_skus_callback count_skus;
    public get_sku_callback get_sku;
    public get_sku_at_callback get_sku_at;
    public fetch_entitlements_callback fetch_entitlements;
    public count_entitlements_callback count_entitlements;
    public get_entitlement_callback get_entitlement;
    public get_entitlement_at_callback get_entitlement_at;
    public has_sku_entitlement_callback has_sku_entitlement;
    public start_purchase_callback start_purchase;

    public IDiscordStoreManager() {
        super();
    }

	public IDiscordStoreManager(Pointer peer) {
        super(peer);
    }

	protected List<String> getFieldOrder() {
        return Arrays.asList("fetch_skus", "count_skus", "get_sku", "get_sku_at", "fetch_entitlements", "count_entitlements", "get_entitlement", "get_entitlement_at", "has_sku_entitlement", "start_purchase");
    }

	public interface fetch_skus_callback_callback_callback extends Callback {
        void apply(Pointer callback_data, int result);
    }

	public interface fetch_skus_callback extends Callback {
        void apply(IDiscordStoreManager manager, Pointer callback_data, fetch_skus_callback_callback_callback callback);
    }

	public interface count_skus_callback extends Callback {
        void apply(IDiscordStoreManager manager, IntByReference count);
    }

	public interface get_sku_callback extends Callback {
        int apply(IDiscordStoreManager manager, long sku_id, DiscordSku sku);
    }

	public interface get_sku_at_callback extends Callback {
        int apply(IDiscordStoreManager manager, int index, DiscordSku sku);
    }

	public interface fetch_entitlements_callback_callback_callback extends Callback {
        void apply(Pointer callback_data, int result);
    }

	public interface fetch_entitlements_callback extends Callback {
        void apply(IDiscordStoreManager manager, Pointer callback_data, fetch_entitlements_callback_callback_callback callback);
    }

	public interface count_entitlements_callback extends Callback {
        void apply(IDiscordStoreManager manager, IntByReference count);
    }

	public interface get_entitlement_callback extends Callback {
        int apply(IDiscordStoreManager manager, long entitlement_id, DiscordEntitlement entitlement);
    }

	public interface get_entitlement_at_callback extends Callback {
        int apply(IDiscordStoreManager manager, int index, DiscordEntitlement entitlement);
    }

	public interface has_sku_entitlement_callback extends Callback {
        int apply(IDiscordStoreManager manager, long sku_id, Pointer has_entitlement);
    }

    public interface start_purchase_callback_callback_callback extends Callback {
        void apply(Pointer callback_data, int result);
    }

    public interface start_purchase_callback extends Callback {
        void apply(IDiscordStoreManager manager, long sku_id, Pointer callback_data, start_purchase_callback_callback_callback callback);
    }

    public static class ByReference extends IDiscordStoreManager implements Structure.ByReference {

    }

	public static class ByValue extends IDiscordStoreManager implements Structure.ByValue {

    }

}
