package io.github.juanmuscaria.jmutils.discord.game.struct;

import com.sun.jna.Callback;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;

import java.util.Collections;
import java.util.List;

/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class IDiscordOverlayEvents extends Structure {
    public on_toggle_callback on_toggle;

    public IDiscordOverlayEvents() {
        super();
    }

    public IDiscordOverlayEvents(on_toggle_callback on_toggle) {
        super();
        this.on_toggle = on_toggle;
    }

    public IDiscordOverlayEvents(Pointer peer) {
        super(peer);
    }

    protected List<String> getFieldOrder() {
        return Collections.singletonList("on_toggle");
    }

    public interface on_toggle_callback extends Callback {
        void apply(Pointer event_data, byte locked);
    }

    public static class ByReference extends IDiscordOverlayEvents implements Structure.ByReference {

    }

    public static class ByValue extends IDiscordOverlayEvents implements Structure.ByValue {

    }

}
