package io.github.juanmuscaria.jmutils.discord.game.struct;

import com.sun.jna.Callback;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import com.sun.jna.ptr.IntByReference;
import com.sun.jna.ptr.LongByReference;
import com.sun.jna.ptr.PointerByReference;

import java.util.Arrays;
import java.util.List;

/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class IDiscordLobbyManager extends Structure {
    public get_lobby_create_transaction_callback get_lobby_create_transaction;
    public get_lobby_update_transaction_callback get_lobby_update_transaction;
    public get_member_update_transaction_callback get_member_update_transaction;
    public create_lobby_callback create_lobby;
    public update_lobby_callback update_lobby;
    public delete_lobby_callback delete_lobby;
    public connect_lobby_callback connect_lobby;
    public connect_lobby_with_activity_secret_callback connect_lobby_with_activity_secret;
    public disconnect_lobby_callback disconnect_lobby;
    public get_lobby_callback get_lobby;
    public get_lobby_activity_secret_callback get_lobby_activity_secret;
    public get_lobby_metadata_value_callback get_lobby_metadata_value;
    public get_lobby_metadata_key_callback get_lobby_metadata_key;
    public lobby_metadata_count_callback lobby_metadata_count;
    public member_count_callback member_count;
    public get_member_user_id_callback get_member_user_id;
    public get_member_user_callback get_member_user;
    public get_member_metadata_value_callback get_member_metadata_value;
    public get_member_metadata_key_callback get_member_metadata_key;
    public member_metadata_count_callback member_metadata_count;
    public update_member_callback update_member;
    public send_lobby_message_callback send_lobby_message;
    public get_search_query_callback get_search_query;
    public search_callback search;
    public lobby_count_callback lobby_count;
    public get_lobby_id_callback get_lobby_id;
    public connect_voice_callback connect_voice;
    public disconnect_voice_callback disconnect_voice;
    public connect_network_callback connect_network;
    public disconnect_network_callback disconnect_network;
    public flush_network_callback flush_network;
    public open_network_channel_callback open_network_channel;
    public send_network_message_callback send_network_message;

    public IDiscordLobbyManager() {
        super();
    }

    public IDiscordLobbyManager(Pointer peer) {
        super(peer);
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("get_lobby_create_transaction", "get_lobby_update_transaction", "get_member_update_transaction", "create_lobby", "update_lobby", "delete_lobby", "connect_lobby", "connect_lobby_with_activity_secret", "disconnect_lobby", "get_lobby", "get_lobby_activity_secret", "get_lobby_metadata_value", "get_lobby_metadata_key", "lobby_metadata_count", "member_count", "get_member_user_id", "get_member_user", "get_member_metadata_value", "get_member_metadata_key", "member_metadata_count", "update_member", "send_lobby_message", "get_search_query", "search", "lobby_count", "get_lobby_id", "connect_voice", "disconnect_voice", "connect_network", "disconnect_network", "flush_network", "open_network_channel", "send_network_message");
    }

    public interface get_lobby_create_transaction_callback extends Callback {
        int apply(IDiscordLobbyManager manager, PointerByReference transaction);
    }

    public interface get_lobby_update_transaction_callback extends Callback {
        int apply(IDiscordLobbyManager manager, long lobby_id, PointerByReference transaction);
    }

    public interface get_member_update_transaction_callback extends Callback {
        int apply(IDiscordLobbyManager manager, long lobby_id, long user_id, PointerByReference transaction);
    }

    public interface create_lobby_callback_callback_callback extends Callback {
        void apply(Pointer callback_data, int result, DiscordLobby lobby);
    }

    public interface create_lobby_callback extends Callback {
        void apply(IDiscordLobbyManager manager, IDiscordLobbyTransaction transaction, Pointer callback_data, create_lobby_callback_callback_callback callback);
    }

    public interface update_lobby_callback_callback_callback extends Callback {
        void apply(Pointer callback_data, int result);
    }

    public interface update_lobby_callback extends Callback {
        void apply(IDiscordLobbyManager manager, long lobby_id, IDiscordLobbyTransaction transaction, Pointer callback_data, update_lobby_callback_callback_callback callback);
    }

    public interface delete_lobby_callback_callback_callback extends Callback {
        void apply(Pointer callback_data, int result);
    }

    public interface delete_lobby_callback extends Callback {
        void apply(IDiscordLobbyManager manager, long lobby_id, Pointer callback_data, delete_lobby_callback_callback_callback callback);
    }

    public interface connect_lobby_callback_callback_callback extends Callback {
        void apply(Pointer callback_data, int result, DiscordLobby lobby);
    }

    public interface connect_lobby_callback extends Callback {
        void apply(IDiscordLobbyManager manager, long lobby_id, Pointer secret, Pointer callback_data, connect_lobby_callback_callback_callback callback);
    }

    public interface connect_lobby_with_activity_secret_callback_callback_callback extends Callback {
        void apply(Pointer callback_data, int result, DiscordLobby lobby);
    }

    public interface connect_lobby_with_activity_secret_callback extends Callback {
        void apply(IDiscordLobbyManager manager, Pointer activity_secret, Pointer callback_data, connect_lobby_with_activity_secret_callback_callback_callback callback);
    }

    public interface disconnect_lobby_callback_callback_callback extends Callback {
        void apply(Pointer callback_data, int result);
    }

    public interface disconnect_lobby_callback extends Callback {
        void apply(IDiscordLobbyManager manager, long lobby_id, Pointer callback_data, disconnect_lobby_callback_callback_callback callback);
    }

    public interface get_lobby_callback extends Callback {
        int apply(IDiscordLobbyManager manager, long lobby_id, DiscordLobby lobby);
    }

    public interface get_lobby_activity_secret_callback extends Callback {
        int apply(IDiscordLobbyManager manager, long lobby_id, Pointer secret);
    }

    public interface get_lobby_metadata_value_callback extends Callback {
        int apply(IDiscordLobbyManager manager, long lobby_id, Pointer key, Pointer value);
    }

    public interface get_lobby_metadata_key_callback extends Callback {
        int apply(IDiscordLobbyManager manager, long lobby_id, int index, Pointer key);
    }

    public interface lobby_metadata_count_callback extends Callback {
        int apply(IDiscordLobbyManager manager, long lobby_id, IntByReference count);
    }

    public interface member_count_callback extends Callback {
        int apply(IDiscordLobbyManager manager, long lobby_id, IntByReference count);
    }

    public interface get_member_user_id_callback extends Callback {
        int apply(IDiscordLobbyManager manager, long lobby_id, int index, LongByReference user_id);
    }

    public interface get_member_user_callback extends Callback {
        int apply(IDiscordLobbyManager manager, long lobby_id, long user_id, DiscordUser user);
    }

    public interface get_member_metadata_value_callback extends Callback {
        int apply(IDiscordLobbyManager manager, long lobby_id, long user_id, Pointer key, Pointer value);
    }

    public interface get_member_metadata_key_callback extends Callback {
        int apply(IDiscordLobbyManager manager, long lobby_id, long user_id, int index, Pointer key);
    }

    public interface member_metadata_count_callback extends Callback {
        int apply(IDiscordLobbyManager manager, long lobby_id, long user_id, IntByReference count);
    }

    public interface update_member_callback_callback_callback extends Callback {
        void apply(Pointer callback_data, int result);
    }

    public interface update_member_callback extends Callback {
        void apply(IDiscordLobbyManager manager, long lobby_id, long user_id, IDiscordLobbyMemberTransaction transaction, Pointer callback_data, update_member_callback_callback_callback callback);
    }

    public interface send_lobby_message_callback_callback_callback extends Callback {
        void apply(Pointer callback_data, int result);
    }

    public interface send_lobby_message_callback extends Callback {
        void apply(IDiscordLobbyManager manager, long lobby_id, Pointer data, int data_length, Pointer callback_data, send_lobby_message_callback_callback_callback callback);
    }

    public interface get_search_query_callback extends Callback {
        int apply(IDiscordLobbyManager manager, PointerByReference query);
    }

    public interface search_callback_callback_callback extends Callback {
        void apply(Pointer callback_data, int result);
    }

    public interface search_callback extends Callback {
        void apply(IDiscordLobbyManager manager, IDiscordLobbySearchQuery query, Pointer callback_data, search_callback_callback_callback callback);
    }

    public interface lobby_count_callback extends Callback {
        void apply(IDiscordLobbyManager manager, IntByReference count);
    }

    public interface get_lobby_id_callback extends Callback {
        int apply(IDiscordLobbyManager manager, int index, LongByReference lobby_id);
    }

    public interface connect_voice_callback_callback_callback extends Callback {
        void apply(Pointer callback_data, int result);
    }

    public interface connect_voice_callback extends Callback {
        void apply(IDiscordLobbyManager manager, long lobby_id, Pointer callback_data, connect_voice_callback_callback_callback callback);
    }

    public interface disconnect_voice_callback_callback_callback extends Callback {
        void apply(Pointer callback_data, int result);
    }

    public interface disconnect_voice_callback extends Callback {
        void apply(IDiscordLobbyManager manager, long lobby_id, Pointer callback_data, disconnect_voice_callback_callback_callback callback);
    }

    public interface connect_network_callback extends Callback {
        int apply(IDiscordLobbyManager manager, long lobby_id);
    }

    public interface disconnect_network_callback extends Callback {
        int apply(IDiscordLobbyManager manager, long lobby_id);
    }

    public interface flush_network_callback extends Callback {
        int apply(IDiscordLobbyManager manager);
    }

    public interface open_network_channel_callback extends Callback {
        int apply(IDiscordLobbyManager manager, long lobby_id, byte channel_id, byte reliable);
    }

    public interface send_network_message_callback extends Callback {
        int apply(IDiscordLobbyManager manager, long lobby_id, long user_id, byte channel_id, Pointer data, int data_length);
    }

    public static class ByReference extends IDiscordLobbyManager implements Structure.ByReference {

    }

    public static class ByValue extends IDiscordLobbyManager implements Structure.ByValue {

    }

}
