package io.github.juanmuscaria.jmutils.discord.game.struct;

import com.sun.jna.Callback;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class IDiscordApplicationManager extends Structure {
    public validate_or_exit_callback validate_or_exit;
    public get_current_locale_callback get_current_locale;
    public get_current_branch_callback get_current_branch;
    public get_oauth2_token_callback get_oauth2_token;
    public get_ticket_callback get_ticket;

    public IDiscordApplicationManager() {
        super();
    }

    public IDiscordApplicationManager(validate_or_exit_callback validate_or_exit, get_current_locale_callback get_current_locale, get_current_branch_callback get_current_branch, get_oauth2_token_callback get_oauth2_token, get_ticket_callback get_ticket) {
        super();
        this.validate_or_exit = validate_or_exit;
        this.get_current_locale = get_current_locale;
        this.get_current_branch = get_current_branch;
        this.get_oauth2_token = get_oauth2_token;
        this.get_ticket = get_ticket;
    }

    public IDiscordApplicationManager(Pointer peer) {
        super(peer);
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("validate_or_exit", "get_current_locale", "get_current_branch", "get_oauth2_token", "get_ticket");
    }

    public interface validate_or_exit_callback_callback_callback extends Callback {
        void apply(Pointer callback_data, int result);
    }

    public interface validate_or_exit_callback extends Callback {
        void apply(IDiscordApplicationManager manager, Pointer callback_data, validate_or_exit_callback_callback_callback callback);
    }

    public interface get_current_locale_callback extends Callback {
        void apply(IDiscordApplicationManager manager, Pointer locale);
    }

    public interface get_current_branch_callback extends Callback {
        void apply(IDiscordApplicationManager manager, Pointer branch);
    }

    public interface get_oauth2_token_callback_callback_callback extends Callback {
        void apply(Pointer callback_data, int result, DiscordOAuth2Token oauth2_token);
    }

    public interface get_oauth2_token_callback extends Callback {
        void apply(IDiscordApplicationManager manager, Pointer callback_data, get_oauth2_token_callback_callback_callback callback);
    }

    public interface get_ticket_callback_callback_callback extends Callback {
        void apply(Pointer callback_data, int result, Pointer data);
    }

    public interface get_ticket_callback extends Callback {
        void apply(IDiscordApplicationManager manager, Pointer callback_data, get_ticket_callback_callback_callback callback);
    }

    public static class ByReference extends IDiscordApplicationManager implements Structure.ByReference {

    }

    public static class ByValue extends IDiscordApplicationManager implements Structure.ByValue {

    }

}
